// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	BounceRule           string
	BounceRuleChange     string
	ThroughputRule       string
	ThroughputRuleChange string
}{
	BounceRule:           "bounce_rule",
	BounceRuleChange:     "bounce_rule_change",
	ThroughputRule:       "throughput_rule",
	ThroughputRuleChange: "throughput_rule_change",
}
