// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testBounceRules(t *testing.T) {
	t.Parallel()

	query := BounceRules()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testBounceRulesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BounceRule{}
	if err = randomize.Struct(seed, o, bounceRuleDBTypes, true, bounceRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BounceRules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBounceRulesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BounceRule{}
	if err = randomize.Struct(seed, o, bounceRuleDBTypes, true, bounceRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := BounceRules().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BounceRules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBounceRulesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BounceRule{}
	if err = randomize.Struct(seed, o, bounceRuleDBTypes, true, bounceRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BounceRuleSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BounceRules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBounceRulesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BounceRule{}
	if err = randomize.Struct(seed, o, bounceRuleDBTypes, true, bounceRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := BounceRuleExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if BounceRule exists: %s", err)
	}
	if !e {
		t.Errorf("Expected BounceRuleExists to return true, but got false.")
	}
}

func testBounceRulesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BounceRule{}
	if err = randomize.Struct(seed, o, bounceRuleDBTypes, true, bounceRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	bounceRuleFound, err := FindBounceRule(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if bounceRuleFound == nil {
		t.Error("want a record, got nil")
	}
}

func testBounceRulesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BounceRule{}
	if err = randomize.Struct(seed, o, bounceRuleDBTypes, true, bounceRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = BounceRules().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testBounceRulesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BounceRule{}
	if err = randomize.Struct(seed, o, bounceRuleDBTypes, true, bounceRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := BounceRules().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testBounceRulesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	bounceRuleOne := &BounceRule{}
	bounceRuleTwo := &BounceRule{}
	if err = randomize.Struct(seed, bounceRuleOne, bounceRuleDBTypes, false, bounceRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}
	if err = randomize.Struct(seed, bounceRuleTwo, bounceRuleDBTypes, false, bounceRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = bounceRuleOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = bounceRuleTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := BounceRules().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testBounceRulesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	bounceRuleOne := &BounceRule{}
	bounceRuleTwo := &BounceRule{}
	if err = randomize.Struct(seed, bounceRuleOne, bounceRuleDBTypes, false, bounceRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}
	if err = randomize.Struct(seed, bounceRuleTwo, bounceRuleDBTypes, false, bounceRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = bounceRuleOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = bounceRuleTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BounceRules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func bounceRuleBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *BounceRule) error {
	*o = BounceRule{}
	return nil
}

func bounceRuleAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *BounceRule) error {
	*o = BounceRule{}
	return nil
}

func bounceRuleAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *BounceRule) error {
	*o = BounceRule{}
	return nil
}

func bounceRuleBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *BounceRule) error {
	*o = BounceRule{}
	return nil
}

func bounceRuleAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *BounceRule) error {
	*o = BounceRule{}
	return nil
}

func bounceRuleBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *BounceRule) error {
	*o = BounceRule{}
	return nil
}

func bounceRuleAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *BounceRule) error {
	*o = BounceRule{}
	return nil
}

func bounceRuleBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *BounceRule) error {
	*o = BounceRule{}
	return nil
}

func bounceRuleAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *BounceRule) error {
	*o = BounceRule{}
	return nil
}

func testBounceRulesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &BounceRule{}
	o := &BounceRule{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, bounceRuleDBTypes, false); err != nil {
		t.Errorf("Unable to randomize BounceRule object: %s", err)
	}

	AddBounceRuleHook(boil.BeforeInsertHook, bounceRuleBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	bounceRuleBeforeInsertHooks = []BounceRuleHook{}

	AddBounceRuleHook(boil.AfterInsertHook, bounceRuleAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	bounceRuleAfterInsertHooks = []BounceRuleHook{}

	AddBounceRuleHook(boil.AfterSelectHook, bounceRuleAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	bounceRuleAfterSelectHooks = []BounceRuleHook{}

	AddBounceRuleHook(boil.BeforeUpdateHook, bounceRuleBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	bounceRuleBeforeUpdateHooks = []BounceRuleHook{}

	AddBounceRuleHook(boil.AfterUpdateHook, bounceRuleAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	bounceRuleAfterUpdateHooks = []BounceRuleHook{}

	AddBounceRuleHook(boil.BeforeDeleteHook, bounceRuleBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	bounceRuleBeforeDeleteHooks = []BounceRuleHook{}

	AddBounceRuleHook(boil.AfterDeleteHook, bounceRuleAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	bounceRuleAfterDeleteHooks = []BounceRuleHook{}

	AddBounceRuleHook(boil.BeforeUpsertHook, bounceRuleBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	bounceRuleBeforeUpsertHooks = []BounceRuleHook{}

	AddBounceRuleHook(boil.AfterUpsertHook, bounceRuleAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	bounceRuleAfterUpsertHooks = []BounceRuleHook{}
}

func testBounceRulesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BounceRule{}
	if err = randomize.Struct(seed, o, bounceRuleDBTypes, true, bounceRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BounceRules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBounceRulesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BounceRule{}
	if err = randomize.Struct(seed, o, bounceRuleDBTypes, true); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(bounceRuleColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := BounceRules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBounceRulesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BounceRule{}
	if err = randomize.Struct(seed, o, bounceRuleDBTypes, true, bounceRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBounceRulesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BounceRule{}
	if err = randomize.Struct(seed, o, bounceRuleDBTypes, true, bounceRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BounceRuleSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBounceRulesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BounceRule{}
	if err = randomize.Struct(seed, o, bounceRuleDBTypes, true, bounceRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := BounceRules().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	bounceRuleDBTypes = map[string]string{`ID`: `smallint`, `ResponseCode`: `smallint`, `EnhancedCode`: `varchar`, `Regex`: `varchar`, `Priority`: `tinyint`, `Description`: `varchar`, `BounceAction`: `varchar`}
	_                 = bytes.MinRead
)

func testBounceRulesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(bounceRulePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(bounceRuleAllColumns) == len(bounceRulePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &BounceRule{}
	if err = randomize.Struct(seed, o, bounceRuleDBTypes, true, bounceRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BounceRules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, bounceRuleDBTypes, true, bounceRulePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testBounceRulesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(bounceRuleAllColumns) == len(bounceRulePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &BounceRule{}
	if err = randomize.Struct(seed, o, bounceRuleDBTypes, true, bounceRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BounceRules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, bounceRuleDBTypes, true, bounceRulePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(bounceRuleAllColumns, bounceRulePrimaryKeyColumns) {
		fields = bounceRuleAllColumns
	} else {
		fields = strmangle.SetComplement(
			bounceRuleAllColumns,
			bounceRulePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := BounceRuleSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testBounceRulesUpsert(t *testing.T) {
	t.Parallel()

	if len(bounceRuleAllColumns) == len(bounceRulePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLBounceRuleUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := BounceRule{}
	if err = randomize.Struct(seed, &o, bounceRuleDBTypes, false); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert BounceRule: %s", err)
	}

	count, err := BounceRules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, bounceRuleDBTypes, false, bounceRulePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BounceRule struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert BounceRule: %s", err)
	}

	count, err = BounceRules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
