// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testThroughputRules(t *testing.T) {
	t.Parallel()

	query := ThroughputRules()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testThroughputRulesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThroughputRule{}
	if err = randomize.Struct(seed, o, throughputRuleDBTypes, true, throughputRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ThroughputRules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testThroughputRulesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThroughputRule{}
	if err = randomize.Struct(seed, o, throughputRuleDBTypes, true, throughputRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ThroughputRules().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ThroughputRules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testThroughputRulesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThroughputRule{}
	if err = randomize.Struct(seed, o, throughputRuleDBTypes, true, throughputRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ThroughputRuleSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ThroughputRules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testThroughputRulesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThroughputRule{}
	if err = randomize.Struct(seed, o, throughputRuleDBTypes, true, throughputRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ThroughputRuleExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ThroughputRule exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ThroughputRuleExists to return true, but got false.")
	}
}

func testThroughputRulesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThroughputRule{}
	if err = randomize.Struct(seed, o, throughputRuleDBTypes, true, throughputRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	throughputRuleFound, err := FindThroughputRule(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if throughputRuleFound == nil {
		t.Error("want a record, got nil")
	}
}

func testThroughputRulesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThroughputRule{}
	if err = randomize.Struct(seed, o, throughputRuleDBTypes, true, throughputRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ThroughputRules().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testThroughputRulesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThroughputRule{}
	if err = randomize.Struct(seed, o, throughputRuleDBTypes, true, throughputRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ThroughputRules().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testThroughputRulesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	throughputRuleOne := &ThroughputRule{}
	throughputRuleTwo := &ThroughputRule{}
	if err = randomize.Struct(seed, throughputRuleOne, throughputRuleDBTypes, false, throughputRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}
	if err = randomize.Struct(seed, throughputRuleTwo, throughputRuleDBTypes, false, throughputRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = throughputRuleOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = throughputRuleTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ThroughputRules().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testThroughputRulesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	throughputRuleOne := &ThroughputRule{}
	throughputRuleTwo := &ThroughputRule{}
	if err = randomize.Struct(seed, throughputRuleOne, throughputRuleDBTypes, false, throughputRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}
	if err = randomize.Struct(seed, throughputRuleTwo, throughputRuleDBTypes, false, throughputRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = throughputRuleOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = throughputRuleTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ThroughputRules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func throughputRuleBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ThroughputRule) error {
	*o = ThroughputRule{}
	return nil
}

func throughputRuleAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ThroughputRule) error {
	*o = ThroughputRule{}
	return nil
}

func throughputRuleAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ThroughputRule) error {
	*o = ThroughputRule{}
	return nil
}

func throughputRuleBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ThroughputRule) error {
	*o = ThroughputRule{}
	return nil
}

func throughputRuleAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ThroughputRule) error {
	*o = ThroughputRule{}
	return nil
}

func throughputRuleBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ThroughputRule) error {
	*o = ThroughputRule{}
	return nil
}

func throughputRuleAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ThroughputRule) error {
	*o = ThroughputRule{}
	return nil
}

func throughputRuleBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ThroughputRule) error {
	*o = ThroughputRule{}
	return nil
}

func throughputRuleAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ThroughputRule) error {
	*o = ThroughputRule{}
	return nil
}

func testThroughputRulesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ThroughputRule{}
	o := &ThroughputRule{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, throughputRuleDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ThroughputRule object: %s", err)
	}

	AddThroughputRuleHook(boil.BeforeInsertHook, throughputRuleBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	throughputRuleBeforeInsertHooks = []ThroughputRuleHook{}

	AddThroughputRuleHook(boil.AfterInsertHook, throughputRuleAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	throughputRuleAfterInsertHooks = []ThroughputRuleHook{}

	AddThroughputRuleHook(boil.AfterSelectHook, throughputRuleAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	throughputRuleAfterSelectHooks = []ThroughputRuleHook{}

	AddThroughputRuleHook(boil.BeforeUpdateHook, throughputRuleBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	throughputRuleBeforeUpdateHooks = []ThroughputRuleHook{}

	AddThroughputRuleHook(boil.AfterUpdateHook, throughputRuleAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	throughputRuleAfterUpdateHooks = []ThroughputRuleHook{}

	AddThroughputRuleHook(boil.BeforeDeleteHook, throughputRuleBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	throughputRuleBeforeDeleteHooks = []ThroughputRuleHook{}

	AddThroughputRuleHook(boil.AfterDeleteHook, throughputRuleAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	throughputRuleAfterDeleteHooks = []ThroughputRuleHook{}

	AddThroughputRuleHook(boil.BeforeUpsertHook, throughputRuleBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	throughputRuleBeforeUpsertHooks = []ThroughputRuleHook{}

	AddThroughputRuleHook(boil.AfterUpsertHook, throughputRuleAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	throughputRuleAfterUpsertHooks = []ThroughputRuleHook{}
}

func testThroughputRulesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThroughputRule{}
	if err = randomize.Struct(seed, o, throughputRuleDBTypes, true, throughputRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ThroughputRules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testThroughputRulesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThroughputRule{}
	if err = randomize.Struct(seed, o, throughputRuleDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(throughputRuleColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := ThroughputRules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testThroughputRuleToManyThroughputRuleChanges(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ThroughputRule
	var b, c ThroughputRuleChange

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, throughputRuleDBTypes, true, throughputRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, throughputRuleChangeDBTypes, false, throughputRuleChangeColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, throughputRuleChangeDBTypes, false, throughputRuleChangeColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.ThroughputRuleID = a.ID
	c.ThroughputRuleID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.ThroughputRuleChanges().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.ThroughputRuleID == b.ThroughputRuleID {
			bFound = true
		}
		if v.ThroughputRuleID == c.ThroughputRuleID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := ThroughputRuleSlice{&a}
	if err = a.L.LoadThroughputRuleChanges(ctx, tx, false, (*[]*ThroughputRule)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.ThroughputRuleChanges); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.ThroughputRuleChanges = nil
	if err = a.L.LoadThroughputRuleChanges(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.ThroughputRuleChanges); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testThroughputRuleToManyAddOpThroughputRuleChanges(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ThroughputRule
	var b, c, d, e ThroughputRuleChange

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, throughputRuleDBTypes, false, strmangle.SetComplement(throughputRulePrimaryKeyColumns, throughputRuleColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*ThroughputRuleChange{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, throughputRuleChangeDBTypes, false, strmangle.SetComplement(throughputRuleChangePrimaryKeyColumns, throughputRuleChangeColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*ThroughputRuleChange{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddThroughputRuleChanges(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.ThroughputRuleID {
			t.Error("foreign key was wrong value", a.ID, first.ThroughputRuleID)
		}
		if a.ID != second.ThroughputRuleID {
			t.Error("foreign key was wrong value", a.ID, second.ThroughputRuleID)
		}

		if first.R.ThroughputRule != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.ThroughputRule != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.ThroughputRuleChanges[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.ThroughputRuleChanges[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.ThroughputRuleChanges().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testThroughputRulesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThroughputRule{}
	if err = randomize.Struct(seed, o, throughputRuleDBTypes, true, throughputRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testThroughputRulesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThroughputRule{}
	if err = randomize.Struct(seed, o, throughputRuleDBTypes, true, throughputRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ThroughputRuleSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testThroughputRulesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ThroughputRule{}
	if err = randomize.Struct(seed, o, throughputRuleDBTypes, true, throughputRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ThroughputRules().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	throughputRuleDBTypes = map[string]string{`ID`: `int`, `MXDomain`: `varchar`, `MaxConnections`: `int`, `MessagesPerConnection`: `int`, `ConnectionTTLMillis`: `int`}
	_                     = bytes.MinRead
)

func testThroughputRulesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(throughputRulePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(throughputRuleAllColumns) == len(throughputRulePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ThroughputRule{}
	if err = randomize.Struct(seed, o, throughputRuleDBTypes, true, throughputRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ThroughputRules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, throughputRuleDBTypes, true, throughputRulePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testThroughputRulesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(throughputRuleAllColumns) == len(throughputRulePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ThroughputRule{}
	if err = randomize.Struct(seed, o, throughputRuleDBTypes, true, throughputRuleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ThroughputRules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, throughputRuleDBTypes, true, throughputRulePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(throughputRuleAllColumns, throughputRulePrimaryKeyColumns) {
		fields = throughputRuleAllColumns
	} else {
		fields = strmangle.SetComplement(
			throughputRuleAllColumns,
			throughputRulePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ThroughputRuleSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testThroughputRulesUpsert(t *testing.T) {
	t.Parallel()

	if len(throughputRuleAllColumns) == len(throughputRulePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLThroughputRuleUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ThroughputRule{}
	if err = randomize.Struct(seed, &o, throughputRuleDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ThroughputRule: %s", err)
	}

	count, err := ThroughputRules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, throughputRuleDBTypes, false, throughputRulePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ThroughputRule struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ThroughputRule: %s", err)
	}

	count, err = ThroughputRules().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
